### ISSUE TITLE
[1.12.2] Thrown Projectiles dupe bug.

### ISSUE THREAD

**Issue by SonicX8000** [Cookiehook/Minecraft-Liquid-Enchanting#22] opened 2020-03-25 17:53 UTC
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
AoA3-3.2.6
jei_1.12.2-4.15.0.291
liquidenchanting-1.12.2_v4

-----

Note:
I encounter this with Snowballs at first but I think maybe due to a mod allowing me to stack up to 64 instead of 16 which could've broke a crafting check, however...

Advent of Ascension adds in A LOT of weapons & such. Some are Swords, Guns, Blasters, Bows, etc... but... you can Enchant it's Thrown Weapons which may seem harmless since the effects don't work unless you use melee with them...
![](https://cdn.discordapp.com/attachments/377171551155650560/692426959816491048/thrownprojectiledupe.PNG)
Left:
I put in these Hellfire items which are throwables to inflict damage. I enchant them with Instant Damage II which... somehow let's me so I went through wit the crafting...

Right:
...oh, the crafting recipe took one of the Hellfires but I crafted 64 of them. Somehow I discovered the power of duping items.

=====

This may apply for any thrown item although I'll have to check which ones are effected. Unless this is a recipe derp or something.

*EDIT*
The Cyclic mod let's you stack Snowballs up to 64 however... by itself you cannot apply Potion Effects to them so... gotta hunt down which mod is allowing them to be enchanted. Although... the idea of inflicting potion effects with snowballs is... something.

**Comment by Cookiehook** [comment] 2020-03-25 22:19
Confirmed. It's due to my custom crafting code, that just copies the entire input stack, and the fact that  it only consumes one item from the ingredient stack as it's based on vanilla's recipes.

Initial fix is to set the copied output stacksize to 1 before returning to player. I've done a quick check and that works.

It might be sensible to prevent crafting with any stackable items in general, as they're not going to be melee weapons / bows. Still won't fix Tinkers crossbow bolts which only stack to 1 for some reason.

**Comment by SonicX8000** [comment] 2020-03-25 22:28
"Still won't fix Tinkers crossbow bolts which only stack to 1 for some reason."

Huh?

**Comment by Cookiehook** [comment] 2020-03-26 07:36
To clarify:
I'm thinking the best solution would be to only allow enchanting of non-stackable items, as I can't make throwables work anyway, there's no point in crafting them. However, you'd still be able to enchant crossbow bolts (despite their uselessness as liquid enchanted items) as they are non-stackable.

**Comment by Cookiehook** [comment] 2020-03-26 12:40
Fixed, version 5 available from CurseForge.

I implemented the fix by only allowing you to craft with unstackable items. This should outright prevent you from enchanting these throwables, which is ideal as they don't work yet anyway. If I ever get that working in future, I'll remove this restriction, but limit the amount of output to 1 at a time.

**Closed as completed** 2020-03-26 12:41 UTC
Labels: bug
